---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: color-server
---
apiVersion: v1
kind: Service
metadata:
  name: color-server
  namespace: color-server
  labels:
    app.kubernetes.io/name: color-server
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: color-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-server
  namespace: color-server
  labels:
    app.kubernetes.io/name: color-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: color-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: color-server
    spec:
      containers:
        - name: color-server
          image: "local-dev/color-server:latest"
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
              name: grpc
              protocol: TCP
